title: Sunghong Park # your name (or website title) here
logo: "/IMG_SHP.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <b>Post-doctoral Researcher</b> <br>
  <br>
  Life Science Research Institute, <br>
  <b>Korea Advanced Institute of <br>
  Science and Technology (KAIST)</b><br>
  <br>
  E-mail: <a href="mailto:sunghongpark.ai@kaist.ac.kr">sunghongpark.ai@kaist.ac.kr</a><br>
  <a href="https://scholar.google.com/citations?user=qodN5GQAAAAJ&hl=ko&oi=ao">View My Google Scholar Profile</a>   
theme: jekyll-theme-minimal
